# Numpy

## Introduction to NumPy

NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides powerful tools for working with arrays, performing mathematical operations, and optimizing performance.

## Why NumPy?

*   **Efficiency:** NumPy arrays are more memory-efficient and faster than Python lists.
*   **Vectorization:** Operations on arrays are performed element-wise without explicit loops.
*   **Extensive Mathematical Functions:** Linear algebra, random number generation, and statistical functions.

### Installation

In [1]:
!pip install numpy

### Importing Numpy

In [2]:
import numpy as np

## Creating Arrays

In [8]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [14]:
# 2D array
arr2 = np.array([
     [1, 2, 3],
     [4, 5, 6]
])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 3D array
arr3 = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [3, 1, 5]]
])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 1, 5]]])

### Checking Properties

In [11]:
arr1.shape, arr1.ndim, arr1.size, arr1.dtype

((5,), 1, 5, dtype('int64'))

In [12]:
arr2.shape, arr2.ndim, arr2.size, arr2.dtype

((2, 3), 2, 6, dtype('int64'))

In [13]:
arr3.shape, arr3.ndim, arr3.size, arr3.dtype

((2, 2, 3), 3, 12, dtype('int64'))

## Random Number Generation

In [16]:
rand_scores = np.random.randint(50, 100, size=10)
print("Random Scores:", rand_scores)

Random Scores: [93 67 95 54 78 69 60 85 94 56]


In [20]:
np.random.rand(10) # generate numbers between 0 and one

array([0.13338591, 0.12439802, 0.57434596, 0.27278417, 0.47666697,
       0.7111508 , 0.7970117 , 0.63903291, 0.85875943, 0.32754309])

### Indexing and Slicing

In [23]:
rand_scores[4]

np.int64(78)

In [26]:
rand_scores[2:5]

array([95, 54, 78])

In [27]:
arr2[0][2]

np.int64(3)

In [29]:
arr3[1][1][2]

np.int64(5)

### Mathematical Operations

In [31]:
print(np.mean(rand_scores))
print(np.sum(rand_scores))
print(np.min(rand_scores))
print(np.max(rand_scores))

75.1
751
54
95


## Linear Algebra

In [37]:
matrix = np.array([[3, 4], [2, 5]])

det = np.linalg.det(matrix) # Determinant
inv = np.linalg.inv(matrix) # Inverse

print(det)
print(inv)

7.000000000000001
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]
